---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R font-awesome $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH